name: Publish Docs

on:
    push:
        branches: [ main ]
    workflow_dispatch:

jobs:
  build_job:
    runs-on: ubuntu-latest
    name: Build Docs
    steps:
    - uses: actions/checkout@v1
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
        
    - name: Restore Dependencies
      run: dotnet restore drm.Documentation.sln
    
    - name: Build
      run: dotnet build drm.Documentation.sln --configuration Release --no-restore
      
    - uses: nikeee/docfx-action@v1.0.0
      name: Build Documentation
      with:
        args: drm.Documentation/docfx.json
