name: Publish Docs

on:
    push:
        branches: [ main ]
    workflow_dispatch:

permissions:
      id-token: write
      contents: read

jobs:
  build_job:
    runs-on: ubuntu-latest
    name: Build Docs
    steps:
    - uses: actions/checkout@v1
      
    - uses: .github/actions/docfx
      name: Build Documentation
      with:
        args: drm.Documentation/docfx.json
        
    - uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        
    - name: Upload to blob storage
      uses: azure/CLI@v1
      with:
        inlineScript: |
            az storage blob upload-batch --account-name stdrmprddocs --auth-mode key -d '$web' -s drm.Documentation/_site --overwrite
        
    # Azure logout
    - name: logout
      run: |
            az logout
      if: always()
